// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProLivros.Persistence;

#nullable disable

namespace ProLivros.Persistence.Migrations
{
    [DbContext(typeof(ProLivrosAPIContext))]
    [Migration("20231215180524_0000")]
    partial class _0000
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProLivros.Domain.Assunto", b =>
                {
                    b.Property<int>("CodAs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodAs"), 1L, 1);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("CodAs");

                    b.ToTable("Assunto", (string)null);
                });

            modelBuilder.Entity("ProLivros.Domain.Autor", b =>
                {
                    b.Property<int?>("CodAu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("CodAu"), 1L, 1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("CodAu");

                    b.ToTable("Autor", (string)null);
                });

            modelBuilder.Entity("ProLivros.Domain.Livro", b =>
                {
                    b.Property<int?>("Codl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Codl"), 1L, 1);

                    b.Property<string>("AnoPublicacao")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<int?>("AssuntoCodAs")
                        .HasColumnType("int");

                    b.Property<int?>("AutorCodAu")
                        .HasColumnType("int");

                    b.Property<string>("Capa")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<int>("Edicao")
                        .HasColumnType("int");

                    b.Property<string>("Editora")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Codl");

                    b.HasIndex("AssuntoCodAs");

                    b.HasIndex("AutorCodAu");

                    b.ToTable("Livro", (string)null);
                });

            modelBuilder.Entity("ProLivros.Domain.LivroAssunto", b =>
                {
                    b.Property<int>("Assunto_CodAs")
                        .HasColumnType("int");

                    b.Property<int>("Livro_Codl")
                        .HasColumnType("int");

                    b.HasIndex("Assunto_CodAs");

                    b.HasIndex("Livro_Codl");

                    b.ToTable("Livro_Assunto", (string)null);
                });

            modelBuilder.Entity("ProLivros.Domain.LivroAutor", b =>
                {
                    b.Property<int>("Autor_CodAu")
                        .HasColumnType("int");

                    b.Property<int>("Livro_Codl")
                        .HasColumnType("int");

                    b.HasIndex("Autor_CodAu");

                    b.HasIndex("Livro_Codl");

                    b.ToTable("Livro_)Autor", (string)null);
                });

            modelBuilder.Entity("ProLivros.Domain.Livro", b =>
                {
                    b.HasOne("ProLivros.Domain.Assunto", null)
                        .WithMany("Livros")
                        .HasForeignKey("AssuntoCodAs");

                    b.HasOne("ProLivros.Domain.Autor", null)
                        .WithMany("Livros")
                        .HasForeignKey("AutorCodAu");
                });

            modelBuilder.Entity("ProLivros.Domain.LivroAssunto", b =>
                {
                    b.HasOne("ProLivros.Domain.Assunto", "Assunto")
                        .WithMany()
                        .HasForeignKey("Assunto_CodAs")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProLivros.Domain.Livro", "Livro")
                        .WithMany()
                        .HasForeignKey("Livro_Codl")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assunto");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("ProLivros.Domain.LivroAutor", b =>
                {
                    b.HasOne("ProLivros.Domain.Autor", "Autor")
                        .WithMany()
                        .HasForeignKey("Autor_CodAu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProLivros.Domain.Livro", "Livro")
                        .WithMany()
                        .HasForeignKey("Livro_Codl")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("ProLivros.Domain.Assunto", b =>
                {
                    b.Navigation("Livros");
                });

            modelBuilder.Entity("ProLivros.Domain.Autor", b =>
                {
                    b.Navigation("Livros");
                });
#pragma warning restore 612, 618
        }
    }
}
